name: "Deploy to Production"
on:
  push:
    branches:
      - main
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "."
          target: /projects

        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: linuxserver.io
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /projects
            Install dependencies
            npm install

            # # Build the project
            # npm run build

            # # Restart the server (if applicable)
            # pm2 restart all

      # - name: Deploy to production server
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      #     SSH_USER: ${{ secrets.SSH_USER }}
      #     SSH_HOST: ${{ secrets.SSH_HOST }}
      #   run: |
      #     echo "$SSH_PRIVATE_KEY" > private_key.pem
      #     chmod 600 private_key.pem
      #     ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts
      #     scp -i private_key.pem -r ./dist/* "$SSH_USER@$SSH_HOST:/path/to/deploy"